#define SECRET_SSID "YOUR_WIFI_NETWORK_NAME_HERE"
#define SECRET_PASS "YOUR_WIFI_NETWORK_PASSWORD_HERE"
#define SECRET_MQTT_USER "kind-one"
#define SECRET_MQTT_PASS "8e0e6b8813973531"
// the User MQTT_USER and _PASS remain the same
